import type { Content } from "./types";
import { site } from "./site";

export const en: Content = {
  locale: "en",
  dir: "ltr",
  meta: {
    title: "Mohammad Alemzadeh — Senior Back-End Developer & Technical Team Lead",
    description:
      "Mohammad Alemzadeh is a senior back-end developer and technical team lead working with Node.js, TypeScript, MongoDB and system design, and a post-quantum cryptography researcher (ML-KEM, ML-DSA).",
    keywords: [
      "Mohammad Alemzadeh",
      "mmdalam",
      "Senior Back-End Developer",
      "Node.js developer",
      "Technical Team Lead",
      "Post-quantum cryptography",
      "Tehran",
    ],
  },
  nav: [
    { id: "about", label: "About" },
    { id: "skills", label: "Skills" },
    { id: "experience", label: "Experience" },
    { id: "projects", label: "Projects" },
    { id: "education", label: "Education" },
    { id: "contact", label: "Contact" },
  ],
  ui: {
    skip: "Skip to main content",
    switchLang: "فا",
    switchLangHref: "/",
    switchLangLabel: "نسخه فارسی",
    themeToggle: "Toggle light and dark mode",
    downloadCv: "Download CV (PDF, Persian)",
    contactCta: "Get in touch",
    now: "Now",
    latticeCaption: "Lattice L(b₁, b₂) — nearest lattice point to your cursor (CVP)",
    present: "Present",
    viewCode: "Code on GitHub",
    viewSite: "Visit site",
    viewPackage: "npm page",
    copyEmail: "Copy email",
    copied: "Copied",
    menu: "Menu",
    backToTop: "Back to top",
  },
  hero: {
    name: "Mohammad Alemzadeh",
    nameAlt: "محمد عالم‌زاده",
    role: "Senior Back-End Developer · Technical Team Lead",
    focus: "Node.js · TypeScript · MongoDB · System Design",
    lede: "I build software systems that are reliable, scalable and easy to maintain — from architecture and database design to production deployment and leading the team. I also research post-quantum cryptography.",
    nowText:
      "Leading the software development team at Sharif University of Technology's Quantum Engineering & Photonics Technology Research Center",
  },
  about: {
    title: "About",
    paragraphs: [
      "I'm a senior back-end developer and technical team lead focused on building reliable, scalable and maintainable software systems. I currently lead the software development team at the **Quantum Engineering & Photonics Technology Research Center, Sharif University of Technology**, and I'm the senior back-end developer at **PsiKet Academy**, working directly on digital platforms for education, science communication and quantum technology.",
      "My work covers the whole software lifecycle: technical planning, system architecture, back-end development, database design, REST APIs, code review, task coordination, deployment, server management, and bridging technical and non-technical teams. My core stack is **Node.js, TypeScript, JavaScript, MongoDB, REST APIs, Vue.js, Nuxt.js, Linux, Nginx, PM2 and Git**, and I care most about back-end architecture, system design, application security, performance, and products that can keep growing for years.",
      "Alongside my job, I'm writing my master's thesis on **post-quantum cryptography**, focused on **ML-KEM** and **ML-DSA** — where back-end engineering and software security meet quantum resistance.",
    ],
    facts: [
      { label: "Based in", value: "Tehran, Iran" },
      { label: "Languages", value: "Persian (native) · English (technical reading & documentation)" },
      { label: "Military service", value: "Eligible — applying for the alternative service program" },
      { label: "Email", value: site.email, dir: "ltr" },
    ],
  },
  skills: {
    title: "Core skills",
    intro: "The tools and areas I work with every day.",
    groups: [
      { label: "Back-End", items: ["Node.js", "TypeScript", "JavaScript", "NestJS", "Express.js"] },
      { label: "API design", items: ["REST API Design", "Socket.IO", "WebSocket"] },
      { label: "Databases", items: ["MongoDB", "Database Design", "Aggregation", "Indexing", "Mongoose", "Redis"] },
      {
        label: "Architecture",
        items: ["System Architecture", "Microservices", "Clean Architecture", "SOLID", "OOP", "Design Patterns"],
      },
      {
        label: "Security",
        items: ["Application Security", "Authentication (JWT/OAuth)", "Encryption", "Post-Quantum Cryptography"],
      },
      { label: "Deployment & servers", items: ["Linux", "Nginx", "PM2", "SSL", "Docker", "Git", "CI/CD"] },
      { label: "Front-End", items: ["Vue.js", "Nuxt.js"] },
      { label: "Technical leadership", items: ["Technical Leadership", "Code Review", "Team Coordination", "Agile"] },
    ],
  },
  experience: {
    title: "Experience",
    items: [
      {
        role: "Software Development Team Lead",
        org: "Quantum Engineering & Photonics Technology Research Center, Sharif University of Technology",
        meta: "Tehran — full-time, on-site",
        period: "Sep 2024 – Present",
        current: true,
        points: [
          "Lead and contribute to the software systems behind the center's educational, scientific and research activities.",
          "Plan technical solutions and turn scientific and organizational requirements into maintainable software products.",
          "Design the back-end architecture, databases, APIs, authentication flows and internal digital tools.",
          "Coordinate development work and collaboration between developers, researchers, education teams and stakeholders.",
          "Own deployments, production servers, system maintenance and troubleshooting.",
          "Support the center's digital infrastructure and improve the reliability, availability and scalability of its online services.",
          "Contribute to software initiatives at the intersection of computer science, education and quantum technology.",
        ],
      },
      {
        role: "Senior Backend Developer & Technical Team Lead",
        org: "PsiKet Academy",
        meta: "Tehran — full-time, on-site",
        period: "Sep 2024 – Present",
        current: true,
        points: [
          "Lead the design and development of PsiKet's education and quantum-technology platforms.",
          "Design and maintain back-end services, databases and REST APIs with Node.js, TypeScript and MongoDB.",
          "Make technical and architectural decisions based on product needs, scalability, security and maintainability.",
          "Build and maintain authentication, course and content management, a media platform, user dashboards and internal admin tools.",
          "Coordinate work between back-end and front-end developers, designers, the content team and stakeholders.",
          "Review code, root-cause complex technical issues and establish consistent development practices across projects.",
          "Run production deployments and server infrastructure with Linux, Nginx, PM2, SSL and Git, improving performance, stability and security.",
        ],
      },
      {
        role: "Software Developer — Freelance",
        org: "Independent projects",
        meta: "Tehran",
        period: "Dec 2020 – Jul 2024",
        points: [
          "Designed and delivered 7+ websites and web applications end to end — from requirements and database design to deployment and support.",
          "Built back ends with Node.js/Express and MongoDB and contributed to front-end development.",
          "Worked directly with clients on scope, time and cost estimates, staged delivery and post-launch support; several products are still in production.",
        ],
      },
    ],
  },
  projects: {
    title: "Selected projects",
    intro: "Some of the things I've built from scratch to production.",
    items: [
      {
        title: "auto-bind-js",
        description:
          "Open-source JavaScript package that automatically binds class methods to their instance, with include/exclude filters, a decorator pattern, inheritance and lazy binding.",
        year: "2025",
        kind: "Open-source package · npm",
        cover: "npm i auto-bind-js",
        stack: ["JavaScript", "npm"],
        links: [
          { label: "npm page", href: "https://www.npmjs.com/package/auto-bind-js" },
          { label: "Code on GitHub", href: "https://github.com/MMDALEM/auto-bind-js" },
        ],
      },
      {
        title: "Sports equipment online store",
        description: "E-commerce platform with cart, payment and inventory management.",
        year: "2025",
        kind: "Online store",
        stack: [],
        links: [],
      },
      {
        title: "Online car logbook",
        description: "Web app for recording and tracking a car's service history and ownership.",
        year: "2024",
        kind: "Web app",
        image: "/images/projects/car-log.jpg",
        stack: [],
        links: [{ label: "API code on GitHub", href: "https://github.com/MMDALEM/api_kartSVC" }],
      },
      {
        title: "Marriage academy website",
        description: "Learning platform with course management, enrollment and multimedia content.",
        year: "2023",
        kind: "Learning platform",
        image: "/images/projects/marriage-academy.jpg",
        stack: ["Node.js"],
        links: [{ label: "Visit site", href: "https://mohammadeydi.ir/" }],
      },
      {
        title: "Accounting & inventory system",
        description: "Finance and stock management app for a small business, including invoice printing.",
        year: "2022",
        kind: "Desktop app",
        image: "/images/projects/accounting.jpg",
        stack: ["Node.js", "Electron.js"],
        links: [{ label: "Code on GitHub", href: "https://github.com/MMDALEM/mardanishop" }],
      },
      {
        title: "University class scheduler",
        description: "Manages class timetables and conflicts, attendance, and instructor–student communication.",
        year: "2021",
        kind: "Desktop app",
        image: "/images/projects/classuni.jpg",
        stack: ["Node.js", "Electron.js"],
        links: [{ label: "Code on GitHub", href: "https://github.com/MMDALEM/ClassUni" }],
      },
    ],
  },
  education: {
    title: "Education & research",
    degree: "M.Sc. in Computer Engineering — Software",
    school: "Islamic Azad University, North Tehran Branch",
    period: "2023 – Present",
    thesisLabel: "Thesis",
    thesisTitle: "Post-quantum cryptography",
    thesisText:
      "A study of quantum-resistant key-encapsulation and digital-signature schemes, their security properties, implementation considerations, and how to integrate them into modern software systems.",
    thesisTags: ["ML-KEM", "ML-DSA", "Lattice-based Crypto", "NIST PQC"],
    honorsTitle: "Honors & courses",
    honors: [
      { title: "Outstanding student researcher", detail: "2022" },
      { title: "Complete Node.js & Express.js course", detail: "Botostart — 590 sessions (2022, certified)" },
      { title: "Building RESTful APIs with Node.js", detail: "Rocket (2020, certified)" },
      { title: "Node.js, Express, MongoDB & More: The Complete Bootcamp", detail: "Udemy (2019)" },
    ],
  },
  contact: {
    title: "Contact",
    text: "For collaboration, technical consulting or job opportunities, reach me by email or phone.",
    emailLabel: "Email",
    phoneLabel: "Phone",
    locationLabel: "Based in",
    location: "Tehran, Iran",
    elsewhere: "Elsewhere",
  },
  footer: {
    line: "Mohammad Alemzadeh — Senior Back-End Developer & Technical Team Lead",
    source: "Site source",
  },
};
