import type { Content } from "./types";
import { site } from "./site";

export const fa: Content = {
  locale: "fa",
  dir: "rtl",
  meta: {
    title: "محمد عالم‌زاده — توسعه‌دهنده ارشد Back-End و سرپرست فنی تیم",
    description:
      "محمد عالم‌زاده؛ توسعه‌دهنده ارشد Back-End و سرپرست فنی تیم توسعه، متخصص Node.js، TypeScript، MongoDB و طراحی سیستم، و پژوهشگر رمزنگاری پساکوانتومی (ML-KEM و ML-DSA).",
    keywords: [
      "محمد عالم‌زاده",
      "عالم زاده",
      "Mohammad Alemzadeh",
      "mmdalam",
      "ممد عالم",
      "توسعه‌دهنده Back-End",
      "برنامه‌نویس Node.js",
      "سرپرست تیم توسعه",
      "رمزنگاری پساکوانتومی",
    ],
  },
  nav: [
    { id: "about", label: "درباره من" },
    { id: "skills", label: "مهارت‌ها" },
    { id: "experience", label: "سوابق" },
    { id: "projects", label: "پروژه‌ها" },
    { id: "education", label: "تحصیلات" },
    { id: "contact", label: "تماس" },
  ],
  ui: {
    skip: "رفتن به محتوای اصلی",
    switchLang: "EN",
    switchLangHref: "/en",
    switchLangLabel: "English version",
    themeToggle: "تغییر حالت روشن و تاریک",
    downloadCv: "دانلود رزومه (PDF)",
    contactCta: "ارتباط با من",
    now: "اکنون",
    latticeCaption: "شبکهٔ مشبکه — نزدیک‌ترین نقطهٔ شبکه به نشانگر (CVP)",
    present: "اکنون",
    viewCode: "کد در GitHub",
    viewSite: "مشاهده سایت",
    viewPackage: "صفحه npm",
    copyEmail: "کپی ایمیل",
    copied: "کپی شد",
    menu: "منو",
    backToTop: "بازگشت به بالا",
  },
  hero: {
    name: "محمد عالم‌زاده",
    nameAlt: "Mohammad Alemzadeh",
    role: "توسعه‌دهنده ارشد Back-End · سرپرست فنی تیم توسعه",
    focus: "Node.js · TypeScript · MongoDB · System Design",
    lede: "سامانه‌های نرم‌افزاری قابل اتکا، مقیاس‌پذیر و قابل نگهداری می‌سازم؛ از معماری و طراحی پایگاه داده تا استقرار در Production و هدایت تیم. پژوهشگر رمزنگاری پساکوانتومی هم هستم.",
    nowText:
      "سرپرست تیم توسعه نرم‌افزار در مرکز تحقیقات مهندسی کوانتوم و فناوری‌های فوتونیک دانشگاه صنعتی شریف",
  },
  about: {
    title: "درباره من",
    paragraphs: [
      "توسعه‌دهنده ارشد Back-End و سرپرست فنی تیم توسعه هستم و روی ساخت سامانه‌های نرم‌افزاری قابل اتکا، مقیاس‌پذیر و قابل نگهداری تمرکز دارم. هم‌اکنون سرپرست تیم توسعه نرم‌افزار **مرکز تحقیقات مهندسی کوانتوم و فناوری‌های فوتونیک دانشگاه صنعتی شریف** و توسعه‌دهنده ارشد **آکادمی سایکت** هستم و در ساخت پلتفرم‌های دیجیتال حوزه آموزش، ارتباطات علمی و فناوری کوانتومی نقش مستقیم دارم.",
      "مسئولیت‌هایم کل چرخه عمر توسعه نرم‌افزار را پوشش می‌دهد: برنامه‌ریزی فنی، معماری سیستم، توسعه Back-End، طراحی پایگاه داده، توسعه REST API، بازبینی کد، هماهنگی وظایف، استقرار، مدیریت سرور و ایجاد ارتباط میان تیم‌های فنی و غیر فنی. استک اصلی من **Node.js، TypeScript، JavaScript، MongoDB، REST API، Vue.js، Nuxt.js، Linux، Nginx، PM2 و Git** است و به‌طور خاص به معماری Back-End، طراحی سیستم، امنیت نرم‌افزار، بهینه‌سازی کارایی و ساخت محصولاتی که در بلندمدت قابل رشد باشند علاقه دارم.",
      "در کنار کار حرفه‌ای، پایان‌نامه کارشناسی ارشدم را در حوزه **رمزنگاری پساکوانتومی** با تمرکز بر **ML-KEM** و **ML-DSA** در دست تدوین دارم؛ جایی که تجربه مهندسی Back-End و امنیت نرم‌افزار با تخصص در زمینه مقاومت کوانتومی تلاقی می‌کند.",
    ],
    facts: [
      { label: "محل سکونت", value: "تهران، ایران" },
      { label: "زبان", value: "فارسی (زبان مادری) · انگلیسی (مطالعه و مستندات فنی)" },
      { label: "وضعیت خدمت", value: "مشمول — متقاضی امریه / پروژه جایگزین خدمت" },
      { label: "ایمیل", value: site.email, dir: "ltr" },
    ],
  },
  skills: {
    title: "مهارت‌های کلیدی",
    intro: "ابزارها و حوزه‌هایی که هر روز با آن‌ها کار می‌کنم.",
    groups: [
      { label: "توسعه Back-End", items: ["Node.js", "TypeScript", "JavaScript", "NestJS", "Express.js"] },
      { label: "طراحی API", items: ["REST API Design", "Socket.IO", "WebSocket"] },
      { label: "پایگاه داده", items: ["MongoDB", "Database Design", "Aggregation", "Indexing", "Mongoose", "Redis"] },
      {
        label: "معماری",
        items: ["System Architecture", "Microservices", "Clean Architecture", "SOLID", "OOP", "Design Patterns"],
      },
      {
        label: "امنیت",
        items: ["Application Security", "Authentication (JWT/OAuth)", "Encryption", "Post-Quantum Cryptography"],
      },
      { label: "استقرار و سرور", items: ["Linux", "Nginx", "PM2", "SSL", "Docker", "Git", "CI/CD"] },
      { label: "Front-End", items: ["Vue.js", "Nuxt.js"] },
      { label: "رهبری فنی", items: ["Technical Leadership", "Code Review", "Team Coordination", "Agile"] },
    ],
  },
  experience: {
    title: "سوابق شغلی",
    items: [
      {
        role: "سرپرست تیم توسعه نرم‌افزار",
        roleAlt: "Software Development Team Lead",
        org: "مرکز تحقیقات مهندسی کوانتوم و فناوری‌های فوتونیک، دانشگاه صنعتی شریف",
        meta: "تهران — تمام‌وقت، حضوری",
        period: "شهریور ۱۴۰۳ – اکنون",
        current: true,
        points: [
          "راهبری و مشارکت در توسعه سامانه‌های نرم‌افزاری پشتیبان فعالیت‌های آموزشی، علمی و پژوهشی مرکز.",
          "برنامه‌ریزی راهکارهای فنی و تبدیل نیازمندی‌های علمی و سازمانی به محصولات نرم‌افزاری قابل نگهداری.",
          "طراحی معماری Back-End، پایگاه داده، APIها، جریان‌های احراز هویت و ابزارهای دیجیتال داخلی سازمان.",
          "هماهنگی وظایف توسعه و تسهیل همکاری میان توسعه‌دهندگان، پژوهشگران، تیم‌های آموزشی و ذی‌نفعان پروژه.",
          "مدیریت فرایندهای استقرار، سرورهای Production، نگهداشت سیستم و رفع اشکالات فنی.",
          "پشتیبانی از زیرساخت دیجیتال مرکز و ارتقای پایداری، دسترس‌پذیری و مقیاس‌پذیری سرویس‌های آنلاین.",
          "مشارکت در ابتکارات نرم‌افزاری در تلاقی علوم کامپیوتر، آموزش و فناوری‌های کوانتومی.",
        ],
      },
      {
        role: "توسعه‌دهنده ارشد Back-End و سرپرست فنی تیم",
        roleAlt: "Senior Backend Developer & Technical Team Lead",
        org: "آکادمی سایکت (PsiKet Academy)",
        meta: "تهران — تمام‌وقت، حضوری",
        period: "شهریور ۱۴۰۳ – اکنون",
        current: true,
        points: [
          "راهبری طراحی و توسعه پلتفرم‌های آموزشی و فناوری کوانتومی سایکت.",
          "طراحی و نگهداری سرویس‌های Back-End، پایگاه‌های داده و REST API با Node.js، TypeScript و MongoDB.",
          "اتخاذ تصمیم‌های فنی و معماری بر اساس نیازمندی محصول، مقیاس‌پذیری، امنیت و قابلیت نگهداری.",
          "توسعه و نگهداری سامانه‌های احراز هویت، مدیریت دوره و محتوا، پلتفرم رسانه، داشبورد کاربران و ابزارهای مدیریتی داخلی.",
          "هماهنگی وظایف توسعه میان توسعه‌دهندگان Back-End و Front-End، طراحان، تیم محتوا و ذی‌نفعان پروژه.",
          "بازبینی کد، ریشه‌یابی مسائل فنی پیچیده و استقرار رویه‌های توسعه یکسان در سطح پروژه‌ها.",
          "مدیریت استقرار Production و زیرساخت سرور با Linux، Nginx، PM2، SSL و Git؛ و ارتقای کارایی، پایداری و امنیت سامانه‌های موجود.",
        ],
      },
      {
        role: "توسعه‌دهنده نرم‌افزار — فریلنس",
        org: "پروژه‌های مستقل",
        meta: "تهران",
        period: "دی ۱۳۹۹ – تیر ۱۴۰۳",
        points: [
          "طراحی و تحویل بیش از ۷ وب‌سایت و وب‌اپلیکیشن به‌صورت end-to-end؛ از تحلیل نیازمندی و طراحی پایگاه داده تا استقرار و پشتیبانی.",
          "پیاده‌سازی Back-End با Node.js/Express و MongoDB و مشارکت در توسعه Front-End.",
          "ارتباط مستقیم با کارفرما، برآورد زمان و هزینه، تحویل مرحله‌ای و پشتیبانی پس از استقرار؛ چند محصول همچنان در حال بهره‌برداری است.",
        ],
      },
    ],
  },
  projects: {
    title: "پروژه‌های شاخص",
    intro: "بخشی از کارهایی که از صفر تا استقرار ساخته‌ام.",
    items: [
      {
        title: "auto-bind-js",
        description:
          "پکیج متن‌باز جاوااسکریپت برای اتصال خودکار متدها به نمونه کلاس؛ با پشتیبانی از فیلتر include/exclude، الگوی دکوراتور، ارث‌بری و اتصال تنبل (lazy).",
        year: "۱۴۰۴",
        kind: "پکیج متن‌باز · npm",
        cover: "npm i auto-bind-js",
        stack: ["JavaScript", "npm"],
        links: [
          { label: "صفحه npm", href: "https://www.npmjs.com/package/auto-bind-js" },
          { label: "کد در GitHub", href: "https://github.com/MMDALEM/auto-bind-js" },
        ],
      },
      {
        title: "فروشگاه اینترنتی لوازم ورزشی",
        description: "پلتفرم فروشگاهی با مدیریت سبد خرید، پرداخت و انبار.",
        year: "۱۴۰۴",
        kind: "فروشگاه اینترنتی",
        stack: [],
        links: [],
      },
      {
        title: "وب‌اپلیکیشن دفترچه آنلاین خودرو",
        description: "سامانه ثبت و پیگیری سوابق سرویس و مالکیت خودرو.",
        year: "۱۴۰۳",
        kind: "وب‌اپلیکیشن",
        image: "/images/projects/car-log.jpg",
        stack: [],
        links: [{ label: "کد API در GitHub", href: "https://github.com/MMDALEM/api_kartSVC" }],
      },
      {
        title: "سایت آکادمی ازدواج",
        description: "سامانه آموزشی با مدیریت دوره، ثبت‌نام و محتوای چندرسانه‌ای.",
        year: "۱۴۰۲",
        kind: "پلتفرم آموزشی",
        image: "/images/projects/marriage-academy.jpg",
        stack: ["Node.js"],
        links: [{ label: "مشاهده سایت", href: "https://mohammadeydi.ir/" }],
      },
      {
        title: "سامانه حسابداری و انبارداری",
        description: "اپلیکیشن مدیریت مالی و موجودی برای کسب‌وکار کوچک، همراه با صدور و چاپ فاکتور.",
        year: "۱۴۰۱",
        kind: "اپلیکیشن دسکتاپ",
        image: "/images/projects/accounting.jpg",
        stack: ["Node.js", "Electron.js"],
        links: [{ label: "کد در GitHub", href: "https://github.com/MMDALEM/mardanishop" }],
      },
      {
        title: "سامانه مدیریت کلاس‌های دانشگاه",
        description: "مدیریت برنامه کلاسی و تداخل‌ها، حضور و غیاب و ارتباط استاد و دانشجو.",
        year: "۱۴۰۰",
        kind: "اپلیکیشن دسکتاپ",
        image: "/images/projects/classuni.jpg",
        stack: ["Node.js", "Electron.js"],
        links: [{ label: "کد در GitHub", href: "https://github.com/MMDALEM/ClassUni" }],
      },
    ],
  },
  education: {
    title: "تحصیلات و پژوهش",
    degree: "کارشناسی ارشد مهندسی کامپیوتر — نرم‌افزار",
    school: "دانشگاه آزاد اسلامی، واحد تهران شمال",
    period: "۱۴۰۲ – اکنون",
    thesisLabel: "پایان‌نامه",
    thesisTitle: "رمزنگاری پساکوانتومی",
    thesisText:
      "بررسی سازوکارهای تبادل کلید و امضای دیجیتال مقاوم در برابر کوانتوم، ویژگی‌های امنیتی، ملاحظات پیاده‌سازی و یکپارچه‌سازی آن‌ها در سامانه‌های نرم‌افزاری مدرن.",
    thesisTags: ["ML-KEM", "ML-DSA", "Lattice-based Crypto", "NIST PQC"],
    honorsTitle: "افتخارات و دوره‌ها",
    honors: [
      { title: "دانشجوی پژوهشگر برگزیده", detail: "۱۴۰۱" },
      { title: "دوره جامع Node.js و Express.js", detail: "بُت‌استارت — ۵۹۰ جلسه (۱۴۰۱، با گواهینامه)" },
      { title: "ساخت RESTful API با Node.js", detail: "روکت (۱۳۹۹، با گواهینامه)" },
      { title: "Node.js, Express, MongoDB & More: The Complete Bootcamp", detail: "Udemy (۱۳۹۸)" },
    ],
  },
  contact: {
    title: "تماس",
    text: "برای همکاری، مشاوره فنی یا فرصت شغلی، از طریق ایمیل یا تلفن در ارتباط باشید.",
    emailLabel: "ایمیل",
    phoneLabel: "تلفن",
    locationLabel: "محل سکونت",
    location: "تهران، ایران",
    elsewhere: "شبکه‌ها",
  },
  footer: {
    line: "محمد عالم‌زاده — توسعه‌دهنده ارشد Back-End و سرپرست فنی تیم",
    source: "کد این سایت",
  },
};
